### ISSUE TITLE
Dream Rejected: No valid instances.

### ISSUE THREAD

**Issue by catboy-asdf** [killfrenzy96/AiyaFrenzyBot#3]
The bot seems to start up fine and is able to connect to the web-ui, but when anyone puts a /dream into any channel (or DM) to the bot the command prompt for the bot shows:
Dream Rejected: No valid instances.
and gets hung up on that indefinitely. 

Any ideas as to why?

**Comment by catboy-asdf** [comment]
@killfrenzy96

**Comment by killfrenzy96** [comment]
Ah sorry for the very late response. This usually  occurs when the WebUI instance does not host the checkpoint model in your models.csv file. Be sure to include the file extension in the line.

Also make sure you supply a model for the 'Default' model as well.

Example:
```
display_name|model_full_name|activator_token|native_resolution
Default|v1-5-pruned-emaonly.safetensors||
stable_diffusion_v1.5|v1-5-pruned-emaonly.safetensors||
```

**Comment by catboy-asdf** [comment]
This solved the problem! Thank you very much!
